buffers { size_kb: 65536 fill_policy: RING_BUFFER }
duration_ms: 45000
data_sources { config { name: "linux.ftrace" ftrace_config {
 ftrace_events: "sched/sched_switch"
 ftrace_events: "sched/sched_waking"
 ftrace_events: "power/cpu_frequency"
 atrace_categories: "gfx"
 atrace_categories: "view"
 atrace_categories: "input"
 atrace_apps: "local.wie.nativeapp.trace"
} } }
data_sources { config { name: "android.surfaceflinger.frametimeline" } }
data_sources { config { name: "linux.process_stats" process_stats_config { scan_all_processes_on_start: true } } }
