[package]
name = "wie-lgt"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[features]
cpu-transcript-capture = ["wie-core-arm/cpu-transcript-capture", "wie-wipi-c/cpu-transcript-capture"]
experimental-thumb-inline = ["wie-core-arm/experimental-thumb-inline"]
experimental-thumb-blocks = ["wie-core-arm/experimental-thumb-blocks"]
experimental-pc-local = ["wie-core-arm/experimental-pc-local"]
experimental-thumb-table = ["wie-core-arm/experimental-thumb-table"]
cpu-profiling = ["wie-core-arm/cpu-profiling"]
cpu-throughput = ["wie-core-arm/cpu-throughput"]

[dependencies]
async-trait = { workspace = true }
bytemuck = { workspace = true }
encoding_rs = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
spin = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

chrono = { version = "^0.4", default-features = false, features = ["alloc"] }
elf = { version = "^0.8" }

jvm = { workspace = true }
jvm-class-proto = { workspace = true }
jvm-types = { workspace = true }
rustjava-runtime = { workspace = true }
wipi-types = { workspace = true, features = ["lgt"] }

wie-backend = { workspace = true }
wie-core-arm = { workspace = true }
wie-jvm-support = { workspace = true }
wie-midp = { workspace = true }
wie-util = { workspace = true }
wie-wipi-c = { workspace = true }
wie-wipi-java = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
