#!/usr/bin/env python3
"""Collect locked Rust dependency notices for the launcher build targets."""

import hashlib
import json
import subprocess
import sys
from functools import lru_cache
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "wie-web/public/licenses/Rust-DEPENDENCIES.txt"
TARGETS = {
    "wasm32-unknown-unknown": "wie-web",
    "aarch64-apple-darwin": "wie-app",
    "aarch64-linux-android": "wie-app",
    "x86_64-pc-windows-msvc": "wie-app",
}
NOTICE_PREFIXES = ("LICENSE", "LICENCE", "COPYING", "COPYRIGHT", "NOTICE")


def dependency_graph(target, root_name):
    result = subprocess.run(
        ["cargo", "metadata", "--locked", "--format-version", "1", "--filter-platform", target],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
    )
    metadata = json.loads(result.stdout)
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    pending = [next(package["id"] for package in metadata["packages"] if package["name"] == root_name)]
    selected = set()
    while pending:
        package_id = pending.pop()
        if package_id in selected:
            continue
        selected.add(package_id)
        pending.extend(
            dependency["pkg"]
            for dependency in nodes[package_id]["deps"]
            if any(kind["kind"] != "dev" for kind in dependency["dep_kinds"])
        )
    return [packages[package_id] for package_id in selected]


def notice_files(package):
    directory = Path(package["manifest_path"]).parent
    files = set()
    if package.get("license_file"):
        path = Path(package["license_file"])
        files.add(path if path.is_absolute() else directory / path)
    for path in directory.iterdir():
        if path.is_file() and path.name.upper().startswith(NOTICE_PREFIXES):
            files.add(path)
        elif path.is_dir() and path.name.lower() in {"license", "licenses", "notices"}:
            files.update(item for item in path.rglob("*") if item.is_file())
    if package["source"] is None and not files:
        return [("LICENSE (workspace)", ROOT / "LICENSE")]
    return sorted((path.relative_to(directory).as_posix(), path) for path in files)


def download(url):
    request = Request(url, headers={"User-Agent": "WIE-Launcher-license-notices"})
    with urlopen(request, timeout=30) as response:
        return response.read()


@lru_cache(maxsize=None)
def github_notices(repository, commit):
    parsed = urlparse(repository)
    if parsed.scheme != "https" or parsed.netloc != "github.com":
        return []
    project = parsed.path.strip("/").removesuffix(".git")
    if len(project.split("/")) != 2 or len(commit) != 40:
        return []
    entries = json.loads(download(f"https://api.github.com/repos/{project}/contents?ref={commit}"))
    notices = []
    for entry in entries:
        if entry["type"] == "file" and entry["name"].upper().startswith(NOTICE_PREFIXES):
            url = f"https://raw.githubusercontent.com/{project}/{commit}/{entry['path']}"
            notices.append((f"{entry['path']} ({url})", download(url)))
    return sorted(notices)


def package_notices(package):
    notices = [(label, path.read_bytes()) for label, path in notice_files(package)]
    if notices:
        return notices
    # Some published workspace crates omit their shared license. Use the exact
    # commit recorded by Cargo when the crate was packaged, never a moving branch.
    vcs_path = Path(package["manifest_path"]).parent / ".cargo_vcs_info.json"
    if vcs_path.is_file() and package.get("repository"):
        vcs = json.loads(vcs_path.read_bytes())
        commit = vcs.get("git", {}).get("sha1")
        if commit:
            notices = github_notices(package["repository"], commit)
            if notices:
                return notices
    if package.get("license") == "MPL-2.0":
        # MPL-covered source files may link to the steward's license rather than
        # include a separate file. Preserve the full named license in the bundle.
        url = "https://www.mozilla.org/media/MPL/2.0/index.txt"
        return [(f"MPL-2.0 ({url})", download(url))]
    return []


def main():
    packages = {}
    targets = {}
    for target, root_name in TARGETS.items():
        for package in dependency_graph(target, root_name):
            key = (package["name"], package["version"], package["source"] or "workspace")
            packages[key] = package
            targets.setdefault(key, set()).add(target)

    lock_hash = hashlib.sha256((ROOT / "Cargo.lock").read_bytes()).hexdigest()
    sections = [
        "WIE Launcher: Rust dependency notices\n",
        "Generated by scripts/generate-rust-notices.py from the locked dependency graphs.\n",
        f"Cargo.lock SHA-256: {lock_hash}\n",
        "Includes production and build dependencies for these targets:\n",
        *(f"- {target}: {name}\n" for target, name in TARGETS.items()),
        "\nEach dependency retains its own copyright and license.\n",
        "License, copyright, and notice files below are copied verbatim.\n",
        "Source archives are available at the exact versioned URLs in each entry.\n",
    ]
    missing = []
    for key in sorted(packages):
        package = packages[key]
        name, version, source = key
        sections.extend([
            "\n" + "=" * 78 + "\n",
            f"{name} {version}\n",
            f"SPDX license expression: {package.get('license') or 'See license file'}\n",
            f"Source: {package.get('repository') or ('https://crates.io/crates/' + name + '/' + version)}\n",
            f"Dependency source: {source}\n",
            f"Targets: {', '.join(sorted(targets[key]))}\n",
        ])
        if package["source"] and package["source"].startswith("registry+"):
            sections.append(f"Source archive: https://static.crates.io/crates/{name}/{name}-{version}.crate\n")
        notices = package_notices(package)
        if not notices:
            missing.append(f"{name} {version}")
            sections.append("MISSING NOTICE FILE: review the package before binary distribution.\n")
        for label, data in notices:
            sections.extend([f"\n--- {label} ---\n", data.decode("utf-8"), "\n"])

    output = "".join(sections)
    if str(ROOT) in output or str(Path.home()) in output:
        raise RuntimeError("Generated notices unexpectedly contain a local build path")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(output.encode("utf-8"))
    print(f"Collected notices for {len(packages)} locked crates into {OUTPUT.relative_to(ROOT)}")
    if missing:
        print("Missing notice files: " + ", ".join(missing), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
